### ISSUE TITLE
[Kustomize] Rendering fails due to duplicate annotation being called

### ISSUE THREAD

**Issue by austiincottrell** [jfrog/jfrog-registry-operator#32]
### Describe the bug

Kustomize generates app.kubernetes.io/name & instance. When you throw this helm chart into kustomize it fails to render due to duplicate label values.

### Current behavior

When you render with kustomize it does not drop the duplicate name and instance fails but fails instead. If you get the helm chart together then call the helm chart in kustomize it will fail to render.

<img width="695" alt="Image" src="https://github.com/user-attachments/assets/87896c4c-60aa-41c9-a2e4-320628845913" />

### Reproduction steps

Helm pull helm chart and untar file

write kustomize file:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jfrog-registry-operator
helmGlobals:
  chartHome: './'
helmCharts:
  - name: jfrog
    namespace: jfrog-operator
    releaseName: jfrog-operator
    valuesFile: values.jfrog-operator.yaml
```

write the values.jfrog-operator.yaml
```yaml
jfrog-registry-operator:
  serviceAccount:
    name: jfrog
    annotations:
       eks.amazonaws.com/role-arn: fill-in
```

Then run the command `kustomize build --enable-helm '.'`

### Expected behavior

For the kustomize to be able to render

### JFrog registry operator version

latest

### Package manager info

2.0.0 helm chart

### Git provider

GitHub

### Operating system type and version

macbook
