### ISSUE TITLE
SecretRotator CRD does not include spec.artifactorySubdomains

### ISSUE THREAD

**Issue by sethamclean** [jfrog/jfrog-registry-operator#37]
### Describe the bug

I think this was a recently added spec entry but as far as I can tell it isn't in the CRD for the SecretRotator.

### Current behavior

2025-06-26T20:21:08.233Z error Kustomization/flux-system.flux-system - Reconciliation failed after 105.528794ms, next try in 10m0s SecretRotator/is-artifactory dry-run failed: failed to create typed patch object (/my-artifactory; apps.jfrog.com/v1alpha1, Kind=SecretRotator): .spec.artifactorySubdomains: field not declared in schema

### JFrog registry operator version

2.1.0

### Package manager info

Flux helm operator

### Git provider

GitHub

### JFrog registry operator configuration yaml file

```
apiVersion: apps.jfrog.com/v1alpha1
kind: SecretRotator
metadata:
  name: my-artifactory
spec:
  artifactoryUrl: https://mydomain
  artifactorySubdomains: [subdomain.mydomain]
  refreshTime: 30m
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: flux-system
  generatedSecrets:
    - secretName: jfrog-access-token-secret
      secretType: docker

```

### Operating system type and version

bottlerocket linx eks
